'use strict'

module.exports = {
  DTELOC: {
    1: 'maison',
    2: 'appartement',
    3: 'dependances',
    4: 'local-commercial-industriel'
  },

  CATEGORIES_LOCAL: {
    AP: 'appartement',
    AT: 'installations-techniques',
    AU: 'installations-techniques',
    CA: 'commerce',
    CB: 'divers',
    CD: 'dependance-commerciale',
    CH: 'chantier',
    CM: 'commerce',
    DC: 'dependance-commerciale',
    DE: 'dependance-batie-isolee',
    LC: 'local-commun',
    MA: 'maison',
    ME: 'maison',
    MP: 'maison',
    PP: 'port-de-plaisance',
    SM: 'sol-de-maison',
    U: 'site-industriel',
    U1: 'gare',
    U2: 'gare',
    U3: 'gare',
    U4: 'gare',
    U5: 'gare',
    U6: 'gare',
    U7: 'gare',
    U8: 'gare',
    U9: 'gare',
    UE: 'installations-techniques',
    UG: 'installations-techniques',
    UN: 'site-industriel',
    US: 'site-industriel'
  },

  CATEGORIES_LOCAL_REVISE: {
    MAG1: 'commerce',
    MAG2: 'commerce',
    MAG3: 'commerce',
    MAG4: 'commerce',
    MAG5: 'commerce',
    MAG6: 'station-service',
    MAG7: 'marche',
    BUR1: 'bureaux',
    BUR2: 'bureaux',
    BUR3: 'bureaux',
    DEP1: 'depot',
    DEP2: 'depot',
    DEP3: 'parc-de-stationnement',
    DEP4: 'parc-de-stationnement',
    DEP5: 'stockage-specifique',
    ATE1: 'atelier-artisanal',
    ATE2: 'atelier-industriel',
    ATE3: 'chenil-vivier',
    HOT1: 'hotel',
    HOT2: 'hotel',
    HOT3: 'hotel',
    HOT4: 'autre-hebergement',
    HOT5: 'residence-hoteliere',
    SPE1: 'salle-de-spectable',
    SPE2: 'terrain-de-sport',
    SPE3: 'salle-de-loisir',
    SPE4: 'terrain-de-camping',
    SPE5: 'terrain-de-camping',
    SPE6: 'etablissement-detente-bien-etre',
    SPE7: 'centre-de-loisirs',
    ENS1: 'ecole-privee',
    ENS2: 'ecole-privee',
    CLI1: 'hopital',
    CLI2: 'centre-medico-social-creche',
    CLI3: 'maison-de-retraite',
    CLI4: 'centre-thermal-reeducation',
    IND1: 'site-industriel',
    IND2: 'carriere',
    EXC1: 'autre-etablissement'
  },

  DNATLC: {
    A: 'Local occupé par un apprenti ou un salarié agricole',
    D: 'DOM = habitation principale occupée par le propriétaire',
    L: 'Location autre que propriétaire ou usufruitier',
    P: 'Occupé par le propriétaire ou l’usufruitier',
    T: 'Location, non affectée à l’habitation, soumise à TVA',
    V: 'Vacant'
  },

  CCONAD: {
    CV: 'Cave',
    GA: 'Garage',
    GR: 'Grenier',
    TR: 'Terrasse',
    BC: 'Bûcher',
    BD: 'Buanderie',
    BX: 'Box',
    CD: 'Chambre de domestique',
    CL: 'Cellier',
    DC: 'Dépendance de local commun',
    GC: 'Grenier/cave',
    GP: 'Garage/parking',
    JH: 'Jardin d\'hiver',
    PA: 'Élément de pur agrément',
    PI: 'Pièce indépendante',
    PK: 'Parking',
    PS: 'Piscine',
    RS: 'Remise',
    SR: 'Serre',
    TT: 'Toiture-terrasse'
  },

  CCOAFF: {
    A: 'Locaux commerciaux et biens divers passibles de la TH',
    B: 'Bâtiment industriel',
    C: 'Commerce',
    E: 'Locaux commerciaux et biens divers non passibles de la TH ni de la TP',
    H: 'Habitation',
    K: 'Locaux administratifs non passibles de la TH',
    L: 'Hôtel',
    P: 'Professionnel',
    S: 'Biens divers passibles de la TH',
    T: 'Terrain industriel'
  }
}
