'use strict'

module.exports = {
  DTELOC: {
    1: 'Maison',
    2: 'Appartement',
    3: 'Dépendances',
    4: 'Local commercial ou industriel'
  },

  CCONLC: {
    AP: 'Appartement',
    AT: 'Shelters des antennes téléphones',
    AU: 'Voies et éléments (ex. : péage) construits sur une autoroute',
    CA: 'Commerce sans boutique',
    CB: 'Local divers',
    CD: 'Dépendance commerciale',
    CH: 'Chantier',
    CM: 'Commerce avec boutique',
    DC: 'Dépendance lieux communs (pour les locaux commerciaux)',
    DE: 'Dépendance bâtie isolée (ex. : garage)',
    LC: 'Local commun (ex. : local à vélos)',
    MA: 'Maison',
    ME: 'Maison exceptionnelle',
    MP: 'Maison partagée par une limite territoriale',
    PP: 'Port de plaisance',
    SM: 'Sol de maison (cas de construction sur sol d’autrui)',
    U: 'Établissement industriel (évalué par méthode comptable)',
    U1: 'Gare',
    U2: 'Gare : triage',
    U3: 'Gare : atelier matériel',
    U4: 'Gare : atelier magasin',
    U5: 'Gare : dépôt – titulaire',
    U6: 'Gare : dépôt – réel',
    U7: 'Gare : matériel transport',
    U8: 'Gare : entretien matériel roulant',
    U9: 'Gare : Station usine',
    UE: 'Transformateur électrique HBTA',
    UG: 'Appareil à gaz',
    UN: 'Usine nucléaire',
    US: 'Établissement industriel (évalué par méthode particulière)'
  },

  DNATLC: {
    A: 'Local occupé par un apprenti ou un salarié agricole',
    D: 'DOM = habitation principale occupée par le propriétaire',
    L: 'Location autre que propriétaire ou usufruitier',
    P: 'Occupé par le propriétaire ou l’usufruitier',
    T: 'Location, non affectée à l’habitation, soumise à TVA',
    V: 'Vacant'
  },

  CCONAD: {
    CV: 'Cave',
    GA: 'Garage',
    GR: 'Grenier',
    TR: 'Terrasse',
    BC: 'Bûcher',
    BD: 'Buanderie',
    BX: 'Box',
    CD: 'Chambre de domestique',
    CL: 'Cellier',
    DC: 'Dépendance de local commun',
    GC: 'Grenier/cave',
    GP: 'Garage/parking',
    JH: 'Jardin d\'hiver',
    PA: 'Élément de pur agrément',
    PI: 'Pièce indépendante',
    PK: 'Parking',
    PS: 'Piscine',
    RS: 'Remise',
    SR: 'Serre',
    TT: 'Toiture-terrasse',
  },

  CCOAFF: {
    A: 'Locaux commerciaux et biens divers passibles de la TH',
    B: 'Bâtiment industriel',
    C: 'Commerce',
    E: 'Locaux commerciaux et biens divers non passibles de la TH ni de la TP',
    H: 'Habitation',
    K: 'Locaux administratifs non passibles de la TH',
    L: 'Hôtel',
    P: 'Professionnel',
    S: 'Biens divers passibles de la TH',
    T: 'Terrain industriel',
  },
}
